###############################################
# Run Mr Coxall's Super Linter against code base #
###############################################

---
name: Mr Coxall's Super Linter
on: push

jobs:
  run-linters:
    name: Mr Coxall's Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Prettify code
        uses: mr-coxall/prettier_action@main
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
          
      - name: Run GitHub Super Linter
        uses: github/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false # standard js linter
          VALIDATE_GITLEAKS: false # for secrets detection
          VALIDATE_JSCPD: false # for copy and paste detection
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
